.\" Manpage for GnuDOS.
.\" Contact mohammed_isam1984@yahoo.com for feedback/corrections.
.TH GnuDOS 1 "JULY 2024" "2.0" "GnuDOS man page"
.SH NAME
GnuDOS \- The GnuDOS library for GNU/Linux Version 2.0
.SH DESCRIPTION
GnuDOS is a group of utilities that were designed to introduce new users to 
the GNU system. The library contains an editor, a file manager, and other 
tools which have a look-and-feel familiar to users of MS-DOS like systems. 
The aim is to provide users accustomed to such systems a gentle way to learn 
how to use the GNU operating system.
.SH FILES
.I "console/screen.h"
The header file defining functions for the Screen utility
.br
.I "console/dialogs.h"
The header file defining functions for the Dialogs utility
.br
.I "console/kbd.h"
The header file defining functions for the Kbd utility
.br
.I "console/ukbd.h"
The header file defining functions for the UKbd utility (Unicode support)
.SH TODO
- Add mouse support
.br
- Add more key definitions to the Kbd utility
.br
- Add printing functionality
.br
- Testing and debugging!
.SH SEE ALSO
info gnudos, info mino, info prime
.SH AUTHOR
Mohammed Isam <mohammed_isam1984@yahoo.com>
